### ISSUE TITLE
在么更新点功能（？

### ISSUE THREAD

**Issue by Longtianmu** [czs233/Synchronize_Custom#1]
最好加个限速 和替换优先级 逻辑应该是先从本地上传，同名文件取最新的，没有的文件直接上传，然后服务器反过来覆盖本地
添加自定义目录

**Comment by czs233** [comment]
每秒更新32KB我都懒得限制了
其他的在写了

**Comment by czs233** [comment]
自定义目录√
其他的功能会在下个大版本推出

**Comment by czs233** [comment]
修完啦！！！
